# Generated by Django 4.1.7 on 2023-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=20)),
                ('escola', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('data_publicacao', models.CharField(max_length=50)),
                ('data_nascimento', models.CharField(max_length=50)),
            ],
        ),
    ]
