# Generated by Django 4.1.7 on 2023-03-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_historicalaluno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalAluno',
        ),
    ]
